# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: lib/tmux-test/setup
  displayName: Test setup

- script: tests/run_tests_in_isolation
  displayName: Run tests
