# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- upstream

pool:
  vmImage: ubuntu-latest

resources:
  containers:
    - container: ubuntu-latest
      image: ubuntu-latest
      options: --interactive --tty

jobs:
  - job: base_job
    container: ubuntu-latest
    steps:
      - checkout: self
        submodules: true

      - script: |
          sudo apt install -y expect
          lib/tmux-test/setup
        displayName: Test setup

      - script: tests/run_tests_in_isolation
        displayName: Run tests
